// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WYKKKCbNDZLbEYnRxOvziIQ5wlZEBT4',
    appId: '1:420220607493:web:a8b34d5b3cc403d0ea106c',
    messagingSenderId: '420220607493',
    projectId: 'fir-flutter-ba165',
    authDomain: 'fir-flutter-ba165.firebaseapp.com',
    storageBucket: 'fir-flutter-ba165.appspot.com',
    measurementId: 'G-SZ8CXGJ6XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCdDKJCbubS8qDFQ0USniV0uhYu-7Z5Y',
    appId: '1:420220607493:android:5e7b6bc02e1ac8beea106c',
    messagingSenderId: '420220607493',
    projectId: 'fir-flutter-ba165',
    storageBucket: 'fir-flutter-ba165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTWhNv7yP5ITTy1WjznXz7GPxWsBRkAhA',
    appId: '1:420220607493:ios:bd19c48db79ff457ea106c',
    messagingSenderId: '420220607493',
    projectId: 'fir-flutter-ba165',
    storageBucket: 'fir-flutter-ba165.appspot.com',
    iosBundleId: 'com.ardirannu.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTWhNv7yP5ITTy1WjznXz7GPxWsBRkAhA',
    appId: '1:420220607493:ios:bd19c48db79ff457ea106c',
    messagingSenderId: '420220607493',
    projectId: 'fir-flutter-ba165',
    storageBucket: 'fir-flutter-ba165.appspot.com',
    iosBundleId: 'com.ardirannu.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8WYKKKCbNDZLbEYnRxOvziIQ5wlZEBT4',
    appId: '1:420220607493:web:a6419cfdc3a7a07dea106c',
    messagingSenderId: '420220607493',
    projectId: 'fir-flutter-ba165',
    authDomain: 'fir-flutter-ba165.firebaseapp.com',
    storageBucket: 'fir-flutter-ba165.appspot.com',
    measurementId: 'G-4QMT0L9YGT',
  );
}
